// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#include "math.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_math_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Vec3Message_math_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_math_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Vec4Message_math_2eproto;
namespace tbMath {
class Vec2MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vec2Message> _instance;
} _Vec2Message_default_instance_;
class Vec3MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vec3Message> _instance;
} _Vec3Message_default_instance_;
class Vec4MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vec4Message> _instance;
} _Vec4Message_default_instance_;
class Mat3MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Mat3Message> _instance;
} _Mat3Message_default_instance_;
class Mat4MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Mat4Message> _instance;
} _Mat4Message_default_instance_;
}  // namespace tbMath
static void InitDefaultsVec2Message_math_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tbMath::_Vec2Message_default_instance_;
    new (ptr) ::tbMath::Vec2Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tbMath::Vec2Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Vec2Message_math_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVec2Message_math_2eproto}, {}};

static void InitDefaultsVec3Message_math_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tbMath::_Vec3Message_default_instance_;
    new (ptr) ::tbMath::Vec3Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tbMath::Vec3Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Vec3Message_math_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVec3Message_math_2eproto}, {}};

static void InitDefaultsVec4Message_math_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tbMath::_Vec4Message_default_instance_;
    new (ptr) ::tbMath::Vec4Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tbMath::Vec4Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Vec4Message_math_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVec4Message_math_2eproto}, {}};

static void InitDefaultsMat3Message_math_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tbMath::_Mat3Message_default_instance_;
    new (ptr) ::tbMath::Mat3Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tbMath::Mat3Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Mat3Message_math_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMat3Message_math_2eproto}, {
      &scc_info_Vec3Message_math_2eproto.base,}};

static void InitDefaultsMat4Message_math_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tbMath::_Mat4Message_default_instance_;
    new (ptr) ::tbMath::Mat4Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tbMath::Mat4Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Mat4Message_math_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMat4Message_math_2eproto}, {
      &scc_info_Vec4Message_math_2eproto.base,}};

void InitDefaults_math_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_Vec2Message_math_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Vec3Message_math_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Vec4Message_math_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Mat3Message_math_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Mat4Message_math_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_math_2eproto[5];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_math_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_math_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_math_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec2Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec2Message, x_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec2Message, y_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec3Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec3Message, x_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec3Message, y_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec3Message, z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec4Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec4Message, x_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec4Message, y_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec4Message, z_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Vec4Message, w_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat3Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat3Message, x_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat3Message, y_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat3Message, z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat4Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat4Message, x_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat4Message, y_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat4Message, z_),
  PROTOBUF_FIELD_OFFSET(::tbMath::Mat4Message, w_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tbMath::Vec2Message)},
  { 7, -1, sizeof(::tbMath::Vec3Message)},
  { 15, -1, sizeof(::tbMath::Vec4Message)},
  { 24, -1, sizeof(::tbMath::Mat3Message)},
  { 32, -1, sizeof(::tbMath::Mat4Message)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tbMath::_Vec2Message_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tbMath::_Vec3Message_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tbMath::_Vec4Message_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tbMath::_Mat3Message_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tbMath::_Mat4Message_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_math_2eproto = {
  {}, AddDescriptors_math_2eproto, "math.proto", schemas,
  file_default_instances, TableStruct_math_2eproto::offsets,
  file_level_metadata_math_2eproto, 5, file_level_enum_descriptors_math_2eproto, file_level_service_descriptors_math_2eproto,
};

const char descriptor_table_protodef_math_2eproto[] =
  "\n\nmath.proto\022\006tbMath\"#\n\013Vec2Message\022\t\n\001x"
  "\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\".\n\013Vec3Message\022\t\n\001x\030\001 "
  "\001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"9\n\013Vec4Message"
  "\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\t\n\001w\030\004"
  " \001(\002\"m\n\013Mat3Message\022\036\n\001x\030\001 \001(\0132\023.tbMath."
  "Vec3Message\022\036\n\001y\030\002 \001(\0132\023.tbMath.Vec3Mess"
  "age\022\036\n\001z\030\003 \001(\0132\023.tbMath.Vec3Message\"\215\001\n\013"
  "Mat4Message\022\036\n\001x\030\001 \001(\0132\023.tbMath.Vec4Mess"
  "age\022\036\n\001y\030\002 \001(\0132\023.tbMath.Vec4Message\022\036\n\001z"
  "\030\003 \001(\0132\023.tbMath.Vec4Message\022\036\n\001w\030\004 \001(\0132\023"
  ".tbMath.Vec4Messageb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_math_2eproto = {
  false, InitDefaults_math_2eproto, 
  descriptor_table_protodef_math_2eproto,
  "math.proto", &assign_descriptors_table_math_2eproto, 427,
};

void AddDescriptors_math_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_math_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_math_2eproto = []() { AddDescriptors_math_2eproto(); return true; }();
namespace tbMath {

// ===================================================================

void Vec2Message::InitAsDefaultInstance() {
}
class Vec2Message::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vec2Message::kXFieldNumber;
const int Vec2Message::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vec2Message::Vec2Message()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tbMath.Vec2Message)
}
Vec2Message::Vec2Message(const Vec2Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:tbMath.Vec2Message)
}

void Vec2Message::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
}

Vec2Message::~Vec2Message() {
  // @@protoc_insertion_point(destructor:tbMath.Vec2Message)
  SharedDtor();
}

void Vec2Message::SharedDtor() {
}

void Vec2Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Vec2Message& Vec2Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Vec2Message_math_2eproto.base);
  return *internal_default_instance();
}


void Vec2Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tbMath.Vec2Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Vec2Message::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Vec2Message*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_x(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_y(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Vec2Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tbMath.Vec2Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tbMath.Vec2Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tbMath.Vec2Message)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Vec2Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tbMath.Vec2Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tbMath.Vec2Message)
}

::google::protobuf::uint8* Vec2Message::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tbMath.Vec2Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tbMath.Vec2Message)
  return target;
}

size_t Vec2Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tbMath.Vec2Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vec2Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tbMath.Vec2Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Vec2Message* source =
      ::google::protobuf::DynamicCastToGenerated<Vec2Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tbMath.Vec2Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tbMath.Vec2Message)
    MergeFrom(*source);
  }
}

void Vec2Message::MergeFrom(const Vec2Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tbMath.Vec2Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void Vec2Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tbMath.Vec2Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vec2Message::CopyFrom(const Vec2Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tbMath.Vec2Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec2Message::IsInitialized() const {
  return true;
}

void Vec2Message::Swap(Vec2Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vec2Message::InternalSwap(Vec2Message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
}

::google::protobuf::Metadata Vec2Message::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_math_2eproto);
  return ::file_level_metadata_math_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Vec3Message::InitAsDefaultInstance() {
}
class Vec3Message::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vec3Message::kXFieldNumber;
const int Vec3Message::kYFieldNumber;
const int Vec3Message::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vec3Message::Vec3Message()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tbMath.Vec3Message)
}
Vec3Message::Vec3Message(const Vec3Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:tbMath.Vec3Message)
}

void Vec3Message::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

Vec3Message::~Vec3Message() {
  // @@protoc_insertion_point(destructor:tbMath.Vec3Message)
  SharedDtor();
}

void Vec3Message::SharedDtor() {
}

void Vec3Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Vec3Message& Vec3Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Vec3Message_math_2eproto.base);
  return *internal_default_instance();
}


void Vec3Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tbMath.Vec3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Vec3Message::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Vec3Message*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_x(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_y(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float z = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_z(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Vec3Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tbMath.Vec3Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tbMath.Vec3Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tbMath.Vec3Message)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Vec3Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tbMath.Vec3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tbMath.Vec3Message)
}

::google::protobuf::uint8* Vec3Message::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tbMath.Vec3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tbMath.Vec3Message)
  return target;
}

size_t Vec3Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tbMath.Vec3Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vec3Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tbMath.Vec3Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Vec3Message* source =
      ::google::protobuf::DynamicCastToGenerated<Vec3Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tbMath.Vec3Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tbMath.Vec3Message)
    MergeFrom(*source);
  }
}

void Vec3Message::MergeFrom(const Vec3Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tbMath.Vec3Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void Vec3Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tbMath.Vec3Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vec3Message::CopyFrom(const Vec3Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tbMath.Vec3Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec3Message::IsInitialized() const {
  return true;
}

void Vec3Message::Swap(Vec3Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vec3Message::InternalSwap(Vec3Message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
}

::google::protobuf::Metadata Vec3Message::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_math_2eproto);
  return ::file_level_metadata_math_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Vec4Message::InitAsDefaultInstance() {
}
class Vec4Message::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vec4Message::kXFieldNumber;
const int Vec4Message::kYFieldNumber;
const int Vec4Message::kZFieldNumber;
const int Vec4Message::kWFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vec4Message::Vec4Message()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tbMath.Vec4Message)
}
Vec4Message::Vec4Message(const Vec4Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&w_) -
    reinterpret_cast<char*>(&x_)) + sizeof(w_));
  // @@protoc_insertion_point(copy_constructor:tbMath.Vec4Message)
}

void Vec4Message::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&x_)) + sizeof(w_));
}

Vec4Message::~Vec4Message() {
  // @@protoc_insertion_point(destructor:tbMath.Vec4Message)
  SharedDtor();
}

void Vec4Message::SharedDtor() {
}

void Vec4Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Vec4Message& Vec4Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Vec4Message_math_2eproto.base);
  return *internal_default_instance();
}


void Vec4Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tbMath.Vec4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&x_)) + sizeof(w_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Vec4Message::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Vec4Message*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_x(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_y(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float z = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_z(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float w = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 37) goto handle_unusual;
        msg->set_w(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Vec4Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tbMath.Vec4Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float w = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (37 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tbMath.Vec4Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tbMath.Vec4Message)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Vec4Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tbMath.Vec4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // float w = 4;
  if (this->w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->w(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tbMath.Vec4Message)
}

::google::protobuf::uint8* Vec4Message::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tbMath.Vec4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // float w = 4;
  if (this->w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->w(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tbMath.Vec4Message)
  return target;
}

size_t Vec4Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tbMath.Vec4Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  // float w = 4;
  if (this->w() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vec4Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tbMath.Vec4Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Vec4Message* source =
      ::google::protobuf::DynamicCastToGenerated<Vec4Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tbMath.Vec4Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tbMath.Vec4Message)
    MergeFrom(*source);
  }
}

void Vec4Message::MergeFrom(const Vec4Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tbMath.Vec4Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.w() != 0) {
    set_w(from.w());
  }
}

void Vec4Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tbMath.Vec4Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vec4Message::CopyFrom(const Vec4Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tbMath.Vec4Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec4Message::IsInitialized() const {
  return true;
}

void Vec4Message::Swap(Vec4Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vec4Message::InternalSwap(Vec4Message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(w_, other->w_);
}

::google::protobuf::Metadata Vec4Message::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_math_2eproto);
  return ::file_level_metadata_math_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Mat3Message::InitAsDefaultInstance() {
  ::tbMath::_Mat3Message_default_instance_._instance.get_mutable()->x_ = const_cast< ::tbMath::Vec3Message*>(
      ::tbMath::Vec3Message::internal_default_instance());
  ::tbMath::_Mat3Message_default_instance_._instance.get_mutable()->y_ = const_cast< ::tbMath::Vec3Message*>(
      ::tbMath::Vec3Message::internal_default_instance());
  ::tbMath::_Mat3Message_default_instance_._instance.get_mutable()->z_ = const_cast< ::tbMath::Vec3Message*>(
      ::tbMath::Vec3Message::internal_default_instance());
}
class Mat3Message::HasBitSetters {
 public:
  static const ::tbMath::Vec3Message& x(const Mat3Message* msg);
  static const ::tbMath::Vec3Message& y(const Mat3Message* msg);
  static const ::tbMath::Vec3Message& z(const Mat3Message* msg);
};

const ::tbMath::Vec3Message&
Mat3Message::HasBitSetters::x(const Mat3Message* msg) {
  return *msg->x_;
}
const ::tbMath::Vec3Message&
Mat3Message::HasBitSetters::y(const Mat3Message* msg) {
  return *msg->y_;
}
const ::tbMath::Vec3Message&
Mat3Message::HasBitSetters::z(const Mat3Message* msg) {
  return *msg->z_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Mat3Message::kXFieldNumber;
const int Mat3Message::kYFieldNumber;
const int Mat3Message::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Mat3Message::Mat3Message()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tbMath.Mat3Message)
}
Mat3Message::Mat3Message(const Mat3Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_x()) {
    x_ = new ::tbMath::Vec3Message(*from.x_);
  } else {
    x_ = nullptr;
  }
  if (from.has_y()) {
    y_ = new ::tbMath::Vec3Message(*from.y_);
  } else {
    y_ = nullptr;
  }
  if (from.has_z()) {
    z_ = new ::tbMath::Vec3Message(*from.z_);
  } else {
    z_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tbMath.Mat3Message)
}

void Mat3Message::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Mat3Message_math_2eproto.base);
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

Mat3Message::~Mat3Message() {
  // @@protoc_insertion_point(destructor:tbMath.Mat3Message)
  SharedDtor();
}

void Mat3Message::SharedDtor() {
  if (this != internal_default_instance()) delete x_;
  if (this != internal_default_instance()) delete y_;
  if (this != internal_default_instance()) delete z_;
}

void Mat3Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Mat3Message& Mat3Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Mat3Message_math_2eproto.base);
  return *internal_default_instance();
}


void Mat3Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tbMath.Mat3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && x_ != nullptr) {
    delete x_;
  }
  x_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && y_ != nullptr) {
    delete y_;
  }
  y_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && z_ != nullptr) {
    delete z_;
  }
  z_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Mat3Message::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Mat3Message*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .tbMath.Vec3Message x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec3Message::_InternalParse;
        object = msg->mutable_x();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tbMath.Vec3Message y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec3Message::_InternalParse;
        object = msg->mutable_y();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tbMath.Vec3Message z = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec3Message::_InternalParse;
        object = msg->mutable_z();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Mat3Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tbMath.Mat3Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tbMath.Vec3Message x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_x()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tbMath.Vec3Message y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_y()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tbMath.Vec3Message z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_z()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tbMath.Mat3Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tbMath.Mat3Message)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Mat3Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tbMath.Mat3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tbMath.Vec3Message x = 1;
  if (this->has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::x(this), output);
  }

  // .tbMath.Vec3Message y = 2;
  if (this->has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::y(this), output);
  }

  // .tbMath.Vec3Message z = 3;
  if (this->has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::z(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tbMath.Mat3Message)
}

::google::protobuf::uint8* Mat3Message::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tbMath.Mat3Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tbMath.Vec3Message x = 1;
  if (this->has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::x(this), target);
  }

  // .tbMath.Vec3Message y = 2;
  if (this->has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::y(this), target);
  }

  // .tbMath.Vec3Message z = 3;
  if (this->has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::z(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tbMath.Mat3Message)
  return target;
}

size_t Mat3Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tbMath.Mat3Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tbMath.Vec3Message x = 1;
  if (this->has_x()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *x_);
  }

  // .tbMath.Vec3Message y = 2;
  if (this->has_y()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *y_);
  }

  // .tbMath.Vec3Message z = 3;
  if (this->has_z()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *z_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Mat3Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tbMath.Mat3Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Mat3Message* source =
      ::google::protobuf::DynamicCastToGenerated<Mat3Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tbMath.Mat3Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tbMath.Mat3Message)
    MergeFrom(*source);
  }
}

void Mat3Message::MergeFrom(const Mat3Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tbMath.Mat3Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_x()) {
    mutable_x()->::tbMath::Vec3Message::MergeFrom(from.x());
  }
  if (from.has_y()) {
    mutable_y()->::tbMath::Vec3Message::MergeFrom(from.y());
  }
  if (from.has_z()) {
    mutable_z()->::tbMath::Vec3Message::MergeFrom(from.z());
  }
}

void Mat3Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tbMath.Mat3Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mat3Message::CopyFrom(const Mat3Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tbMath.Mat3Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mat3Message::IsInitialized() const {
  return true;
}

void Mat3Message::Swap(Mat3Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Mat3Message::InternalSwap(Mat3Message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
}

::google::protobuf::Metadata Mat3Message::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_math_2eproto);
  return ::file_level_metadata_math_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Mat4Message::InitAsDefaultInstance() {
  ::tbMath::_Mat4Message_default_instance_._instance.get_mutable()->x_ = const_cast< ::tbMath::Vec4Message*>(
      ::tbMath::Vec4Message::internal_default_instance());
  ::tbMath::_Mat4Message_default_instance_._instance.get_mutable()->y_ = const_cast< ::tbMath::Vec4Message*>(
      ::tbMath::Vec4Message::internal_default_instance());
  ::tbMath::_Mat4Message_default_instance_._instance.get_mutable()->z_ = const_cast< ::tbMath::Vec4Message*>(
      ::tbMath::Vec4Message::internal_default_instance());
  ::tbMath::_Mat4Message_default_instance_._instance.get_mutable()->w_ = const_cast< ::tbMath::Vec4Message*>(
      ::tbMath::Vec4Message::internal_default_instance());
}
class Mat4Message::HasBitSetters {
 public:
  static const ::tbMath::Vec4Message& x(const Mat4Message* msg);
  static const ::tbMath::Vec4Message& y(const Mat4Message* msg);
  static const ::tbMath::Vec4Message& z(const Mat4Message* msg);
  static const ::tbMath::Vec4Message& w(const Mat4Message* msg);
};

const ::tbMath::Vec4Message&
Mat4Message::HasBitSetters::x(const Mat4Message* msg) {
  return *msg->x_;
}
const ::tbMath::Vec4Message&
Mat4Message::HasBitSetters::y(const Mat4Message* msg) {
  return *msg->y_;
}
const ::tbMath::Vec4Message&
Mat4Message::HasBitSetters::z(const Mat4Message* msg) {
  return *msg->z_;
}
const ::tbMath::Vec4Message&
Mat4Message::HasBitSetters::w(const Mat4Message* msg) {
  return *msg->w_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Mat4Message::kXFieldNumber;
const int Mat4Message::kYFieldNumber;
const int Mat4Message::kZFieldNumber;
const int Mat4Message::kWFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Mat4Message::Mat4Message()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tbMath.Mat4Message)
}
Mat4Message::Mat4Message(const Mat4Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_x()) {
    x_ = new ::tbMath::Vec4Message(*from.x_);
  } else {
    x_ = nullptr;
  }
  if (from.has_y()) {
    y_ = new ::tbMath::Vec4Message(*from.y_);
  } else {
    y_ = nullptr;
  }
  if (from.has_z()) {
    z_ = new ::tbMath::Vec4Message(*from.z_);
  } else {
    z_ = nullptr;
  }
  if (from.has_w()) {
    w_ = new ::tbMath::Vec4Message(*from.w_);
  } else {
    w_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tbMath.Mat4Message)
}

void Mat4Message::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Mat4Message_math_2eproto.base);
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&x_)) + sizeof(w_));
}

Mat4Message::~Mat4Message() {
  // @@protoc_insertion_point(destructor:tbMath.Mat4Message)
  SharedDtor();
}

void Mat4Message::SharedDtor() {
  if (this != internal_default_instance()) delete x_;
  if (this != internal_default_instance()) delete y_;
  if (this != internal_default_instance()) delete z_;
  if (this != internal_default_instance()) delete w_;
}

void Mat4Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Mat4Message& Mat4Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Mat4Message_math_2eproto.base);
  return *internal_default_instance();
}


void Mat4Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tbMath.Mat4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && x_ != nullptr) {
    delete x_;
  }
  x_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && y_ != nullptr) {
    delete y_;
  }
  y_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && z_ != nullptr) {
    delete z_;
  }
  z_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && w_ != nullptr) {
    delete w_;
  }
  w_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Mat4Message::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Mat4Message*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .tbMath.Vec4Message x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec4Message::_InternalParse;
        object = msg->mutable_x();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tbMath.Vec4Message y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec4Message::_InternalParse;
        object = msg->mutable_y();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tbMath.Vec4Message z = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec4Message::_InternalParse;
        object = msg->mutable_z();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tbMath.Vec4Message w = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tbMath::Vec4Message::_InternalParse;
        object = msg->mutable_w();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Mat4Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tbMath.Mat4Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tbMath.Vec4Message x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_x()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tbMath.Vec4Message y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_y()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tbMath.Vec4Message z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_z()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tbMath.Vec4Message w = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_w()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tbMath.Mat4Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tbMath.Mat4Message)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Mat4Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tbMath.Mat4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tbMath.Vec4Message x = 1;
  if (this->has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::x(this), output);
  }

  // .tbMath.Vec4Message y = 2;
  if (this->has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::y(this), output);
  }

  // .tbMath.Vec4Message z = 3;
  if (this->has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::z(this), output);
  }

  // .tbMath.Vec4Message w = 4;
  if (this->has_w()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::w(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tbMath.Mat4Message)
}

::google::protobuf::uint8* Mat4Message::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tbMath.Mat4Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tbMath.Vec4Message x = 1;
  if (this->has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::x(this), target);
  }

  // .tbMath.Vec4Message y = 2;
  if (this->has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::y(this), target);
  }

  // .tbMath.Vec4Message z = 3;
  if (this->has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::z(this), target);
  }

  // .tbMath.Vec4Message w = 4;
  if (this->has_w()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::w(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tbMath.Mat4Message)
  return target;
}

size_t Mat4Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tbMath.Mat4Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tbMath.Vec4Message x = 1;
  if (this->has_x()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *x_);
  }

  // .tbMath.Vec4Message y = 2;
  if (this->has_y()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *y_);
  }

  // .tbMath.Vec4Message z = 3;
  if (this->has_z()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *z_);
  }

  // .tbMath.Vec4Message w = 4;
  if (this->has_w()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *w_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Mat4Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tbMath.Mat4Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Mat4Message* source =
      ::google::protobuf::DynamicCastToGenerated<Mat4Message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tbMath.Mat4Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tbMath.Mat4Message)
    MergeFrom(*source);
  }
}

void Mat4Message::MergeFrom(const Mat4Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tbMath.Mat4Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_x()) {
    mutable_x()->::tbMath::Vec4Message::MergeFrom(from.x());
  }
  if (from.has_y()) {
    mutable_y()->::tbMath::Vec4Message::MergeFrom(from.y());
  }
  if (from.has_z()) {
    mutable_z()->::tbMath::Vec4Message::MergeFrom(from.z());
  }
  if (from.has_w()) {
    mutable_w()->::tbMath::Vec4Message::MergeFrom(from.w());
  }
}

void Mat4Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tbMath.Mat4Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mat4Message::CopyFrom(const Mat4Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tbMath.Mat4Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mat4Message::IsInitialized() const {
  return true;
}

void Mat4Message::Swap(Mat4Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Mat4Message::InternalSwap(Mat4Message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(w_, other->w_);
}

::google::protobuf::Metadata Mat4Message::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_math_2eproto);
  return ::file_level_metadata_math_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tbMath
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::tbMath::Vec2Message* Arena::CreateMaybeMessage< ::tbMath::Vec2Message >(Arena* arena) {
  return Arena::CreateInternal< ::tbMath::Vec2Message >(arena);
}
template<> PROTOBUF_NOINLINE ::tbMath::Vec3Message* Arena::CreateMaybeMessage< ::tbMath::Vec3Message >(Arena* arena) {
  return Arena::CreateInternal< ::tbMath::Vec3Message >(arena);
}
template<> PROTOBUF_NOINLINE ::tbMath::Vec4Message* Arena::CreateMaybeMessage< ::tbMath::Vec4Message >(Arena* arena) {
  return Arena::CreateInternal< ::tbMath::Vec4Message >(arena);
}
template<> PROTOBUF_NOINLINE ::tbMath::Mat3Message* Arena::CreateMaybeMessage< ::tbMath::Mat3Message >(Arena* arena) {
  return Arena::CreateInternal< ::tbMath::Mat3Message >(arena);
}
template<> PROTOBUF_NOINLINE ::tbMath::Mat4Message* Arena::CreateMaybeMessage< ::tbMath::Mat4Message >(Arena* arena) {
  return Arena::CreateInternal< ::tbMath::Mat4Message >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
