actors = {
    { id="ground", name = "ground.lua", position = {0, -4.5, -5} },
    { id="plat_1", name = "platform.lua", position = {-3, -3, -7} },
    { id="plat_2", name = "platform.lua", position = {-5, -3, -7} },
    { id="plat_3", name = "platform.lua", position = {-5, -3, -5} },
    { id="player", name = "human.lua", position = {0, -3, -3}, rotation = {0, 0, 0} },
    { id="", name = "gravity_wand.lua", position = {0, 0, 0}, rotation = {0, 0, 0} },
    { id="", name = "knockback_wand.lua", position = {1, 0, 0}, rotation = {0, 0, 0} },
    { id="", name = "orb_wand.lua", position = {-1, 0, 0}, rotation = {0, 0, 0} },
    { id="", name = "birch.lua", position = {2, -3, -7} },
    { id="", name = "birch.lua", position = {6, -3, -2} },
    { id="", name = "birch.lua", position = {7, -3, -5} },
    { id="", name = "birch.lua", position = {3, -3, -1} },
    { id="", name = "birch.lua", position = {4, -3, 2} },
}
